// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzYr8ZXngyxQ4pd-R3RvduVg4IfyN54PA',
    appId: '1:208592074534:web:0c3e461e0f0464998bb3e7',
    messagingSenderId: '208592074534',
    projectId: 'fixit-d5b5f',
    authDomain: 'fixit-d5b5f.firebaseapp.com',
    storageBucket: 'fixit-d5b5f.appspot.com',
    measurementId: 'G-6ZYJNBXJHZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0YraPI7FQMxFLFK9VqPBSS9PxmUXi2-8',
    appId: '1:208592074534:android:423bac1191c1b2d58bb3e7',
    messagingSenderId: '208592074534',
    projectId: 'fixit-d5b5f',
    storageBucket: 'fixit-d5b5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW3FI0ySxvlxe5rnlVmgAcQywrLDgCqAM',
    appId: '1:208592074534:ios:97e971a3888e8bc98bb3e7',
    messagingSenderId: '208592074534',
    projectId: 'fixit-d5b5f',
    storageBucket: 'fixit-d5b5f.appspot.com',
    iosClientId: '208592074534-77e99ac2rfd12fovt35i7q7eljfe3nqt.apps.googleusercontent.com',
    iosBundleId: 'com.fixit.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW3FI0ySxvlxe5rnlVmgAcQywrLDgCqAM',
    appId: '1:208592074534:ios:97e971a3888e8bc98bb3e7',
    messagingSenderId: '208592074534',
    projectId: 'fixit-d5b5f',
    storageBucket: 'fixit-d5b5f.appspot.com',
    iosClientId: '208592074534-77e99ac2rfd12fovt35i7q7eljfe3nqt.apps.googleusercontent.com',
    iosBundleId: 'com.fixit.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzYr8ZXngyxQ4pd-R3RvduVg4IfyN54PA',
    appId: '1:208592074534:web:da3b8ffcc163d8c98bb3e7',
    messagingSenderId: '208592074534',
    projectId: 'fixit-d5b5f',
    authDomain: 'fixit-d5b5f.firebaseapp.com',
    storageBucket: 'fixit-d5b5f.appspot.com',
    measurementId: 'G-E82ZBP854H',
  );
}
